#+LATEX_COMPILER: xelatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS: [letterpaper,12pt]

#+LATEX_HEADER: \usepackage[margin=2cm]{geometry}

#+LATEX_HEADER: \usepackage{parskip} 
#+LATEX_HEADER: \setlength{\parindent}{0pt} 
#+LATEX_HEADER: \setlength{\parskip}{10pt} 

#+LATEX_HEADER: \usepackage[no-math]{fontspec}
#+LATEX_HEADER: \usepackage{xunicode}
#+LATEX_HEADER: \usepackage{microtype}

#+LATEX_HEADER: \usepackage{fancyhdr}

#+LATEX_HEADER: \setmainfont[Numbers={OldStyle}]{Garamond Premier Pro}
#+LATEX_HEADER: \setsansfont[Scale=MatchLowercase]{Helvetica Neue}
#+LATEX_HEADER: \setmonofont[Scale=1.0]{RobotoMono}
#+LATEX_HEADER: \usepackage[pointlessenum]{paralist}
#+LATEX_HEADER: 
#+LATEX_HEADER: 

#+TITLE:NMSAAM Conflict of Interest Policy
#+DATE: **DRAFT**
#+AUTHOR:
#+OPTIONS: toc:nil

* Purpose and Scope

** Purpose
   The purpose of this Board conflict of interest policy is to protect
   the interests of the New Mexico Society of Acupuncture and Asian
   Medicine, hereafter NMSAAM, when it is contemplating entering into
   a transaction or arrangement that might benefit the private
   interests of an officer or director of NMSAAM or might result in a
   possible excess benefit transaction.

** Scope
   This policy is intended to supplement, but not replace, any
   applicable state and federal laws governing conflicts of interest
   applicable to nonprofit and charitable organizations.

** Independent directors
   This policy is also intended to identify “independent” directors.


* Definitions

** Interested Person
   Any director, principal officer, or member of
   a committee with governing board delegated powers, who has a direct
   or indirect financial interest, as defined below, is an interested
   person.

** Financial Interest
*** Difference From Conflict of Interest
    A financial interest is not necessarily a conflict of interest
*** Conflict of Interest
    /A person who has a financial interest may have a conflict of
    interest only if the Board or Executive Committee decides that a
    conflict of interest exists, in accordance with this policy./
*** Financial Interest
    A person has a financial interest if the person has, directly or
    indirectly, through business, investment, or family:
#+ATTR_LATEX: :options [{2.2.3}.a]
	1. An ownership or investment interest in any entity with which
           NMSAAM has a transaction or arrangement,
	2. A compensation arrangement with NMSAAM or with any entity or
           individual with which NMSAAM has a transaction or arrangement,
           or
	3. A potential ownership or investment interest in, or
           compensation arrangement with, any entity or individual with
           which NMSAAM is negotiating a transaction or arrangement.
** Compensation 
   Compensation includes direct and indirect remuneration as well as gifts or
   favors that are not insubstantial.
** Independent Director
   A director shall be considered “independent” for the purposes of
   this policy if he or she is “independent” as defined in the
   instructions for the IRS 990 form or, until such definition is
   available, the director:
*** Non-employee
    is not, and has not been for a period of at least three years, an
    employee of NMSAAM or any entity in which NMSAAM has a financial
    interest;
*** No Significant Business Relationship
    does not directly or indirectly have a significant business
    relationship with NMSAAM, which might affect independence in
    decision-making;
*** Non-employee of Another Corporation
    is not employed as an executive of another corporation where any
    of NMSAAM’s executive officers or employees serve on that
    corporation’s compensation committee; and
*** Immediate Family
    does not have an immediate family member who is an executive
    officer or employee of NMSAAM or who holds a position that has a
    significant financial relationship with NMSAAM.
** Non-financial Interest
   Is a non-financial interest that might influence an officer’s,
   director’s, or committee member’s participation or vote in an
   action of the officer’s, director’s, or committee member’s duties
   including :
*** Volunteer, Officer, or Director
    The person’s relationship as an unpaid volunteer, officer or
    director of an organization that may be affected, directly or
    indirectly, by action to be taken, or not taken, by NMSAAM; or
*** Personal Relationship
    The person’s personal, political, religious, friendship, or
    personal relationships which may be affected by an action to be
    taken, or not taken, by NMSAAM.
* Procedures
** Duty to Disclose
   In connection with any actual or possible conflict of interest, an
   interested person must disclose the existence of any financial
   interest and be given the opportunity to disclose all material
   facts to the Board or Executive Committee.
** Disclosure of Non-financial Interests
   Directors shall disclose non-financial interests generally in their
   annual statement, and specifically as individual interests
   arise; non-financial interests are expected, and shall not be
   reviewed unless a Board member (including the affected member)
   requests that the interest be reviewed under the Conflict of
   Interest Policy.
** Recusal of Self
   Any director may recuse himself or herself at any time from
   involvement in any decision or discussion in which the director
   believes he or she has or may have a conflict of interest, without
   going through the process for determining whether a conflict of
   interest exists.
** Determining Whether a Conflict of Interest Exists
   After disclosure of the financial interest all material facts will
   be disclosed and reviewed, including discussion with the interested
   person. Upon request by a Board member the material facts of a
   non-financial interest will be reviewed, including discussion with
   the interested party. Then the potentially conflicted Member shall
   leave the Board or Executive Committee meeting while the
   determination of a conflict of interest is discussed and voted
   upon. The remaining Board or Executive Committee members shall
   decide if a conflict of interest exists.
** Procedures for Addressing the Conflict of Interest 
*** Presentation
    An interested person may make a presentation at the Board or
    Executive Committee meeting, but after the presentation, he/she
    shall leave the meeting during the discussion of, and the vote on,
    the transaction, arrangement, or other matter involving the
    possible conflict of interest.
*** Consider Alternatives
    The Chairperson of the Board or Executive Committee shall, if
    appropriate, appoint a disinterested person or committee to
    investigate alternatives to the proposed transaction or
    arrangement.
*** Advantageous Arrangement
    After exercising due diligence, the Board or Executive Committee
    shall determine whether NMSAAM can obtain with reasonable efforts
    a more advantageous transaction or arrangement from a person or
    entity that would not give rise to a financial conflict of
    interest.
*** Decision by Majority Vote
    If a more advantageous transaction or arrangement is not
    reasonably possible under circumstances not producing a financial
    conflict of interest, the Board or Executive Committee shall
    determine by a majority vote of the disinterested directors
    whether the transaction or arrangement is in NMSAAM's best
    interest, for its own benefit, and whether it is fair and
    reasonable. In conformity with the above determination, it shall
    make its decision as to whether to enter into the transaction or
    arrangement.
** Violations of the Conflicts of Interest Policy
*** Reasonable Cause
    If the Board or Executive Committee has reasonable cause to
    believe a member has failed to disclose actual or possible
    conflicts of interest, it shall inform the member of the basis
    for such belief and afford the member an opportunity to explain
    the alleged failure to disclose.
*** Cause for Action
    If, after hearing the member's response and after making further
    investigation as warranted by the circumstances, the Board or
    Executive Committee determines the member has failed to disclose
    an actual or possible conflict of interest, it shall take
    appropriate disciplinary and corrective action.
* Records of Proceedings

  The minutes of the Board and all committees with board delegated
  powers shall contain:
** Record of Disclosures and Findings
   The names of the persons who disclosed or otherwise were found to
   have a financial interest in connection with an actual or
   possible conflict of interest, the nature of the financial
   interest, any action taken to determine whether a conflict of
   interest was present, and the Board's or Executive Committee's
   decision as to whether a conflict of interest in fact existed.
** Record of Those Present
   The names of the persons who were present for discussions and votes
   relating to the transaction or arrangement, the content of the
   discussion, including any alternatives to the proposed transaction
   or arrangement, and a record of any votes taken in connection with
   the proceedings.

* Compensation 

** Board Members
   A voting member of the Board who receives compensation, directly
   or indirectly, from NMSAAM for services is precluded from voting
   on matters pertaining to that member's compensation.

** Committee Members
   A voting member of any committee whose jurisdiction includes
   compensation matters and who receives compensation, directly or
   indirectly, from NMSAAM for services is precluded from voting on
   matters pertaining to that member's compensation.
** Relevant Information
   No voting member of the Board or any committee whose jurisdiction
   includes compensation matters and who receives compensation,
   directly or indirectly, from NMSAAM, either individually or
   collectively, is prohibited from providing information to any
   committee regarding compensation.

* Annual Statements 

** Annual Statement Content
   Each director, principal officer and member of a committee with
   Board delegated powers shall annually sign a statement which
   affirms such person:

*** Received Copy
    Has received a copy of the conflict of interest policy;

*** Read and Understood
    Has read and understands the policy;

*** Agree to Comply
    Has agreed to comply with the policy; and

*** Tax-Exempt Status
    Understands NMSAAM is charitable and in order to maintain its
    federal tax exemption it must engage primarily in activities
    which accomplish one or more of its tax-exempt purposes.
** Annual Statement Independent Director
   Each voting member of the Board shall annually sign a statement
   which declares whether such person is an independent director.
** Changes to Information in Annual Statement
   If at any time during the year, the information in the annual
   statement changes materially, the director shall disclose such
   changes and revise the annual disclosure form.
** Review of Annual Statements
   The Executive Committee shall regularly and consistently monitor
   and enforce compliance with this policy by reviewing annual
   statements and taking such other actions as are necessary for
   effective oversight.
* Periodic Reviews
  To ensure NMSAAM operates in a manner consistent with charitable
  purposes and does not engage in activities that could jeopardize its
  tax-exempt status, periodic reviews shall be conducted. The periodic
  reviews shall, at a minimum, include the following subjects:
#+ATTR_LATEX: :options [{7}.1]
  1. Whether compensation arrangements and benefits are reasonable,
     based on competent survey information (if reasonably available),
     and the result of arm's length bargaining; and
  2. Whether partnerships, joint ventures, and arrangements with
     management organizations, if any, conform to NMSAAM's written
     policies, are properly recorded, reflect reasonable investment or
     payments for goods and services, further charitable purposes and
     do not result in benefit or impermissible private benefit or in
     an excess benefit transaction.
* Use of Outside Experts 
  When conducting the periodic reviews as provided for in Article 7,
  NMSAAM may, but need not, use outside advisors. If outside experts
  are used, their use shall not relieve the Board of its
  responsibility for ensuring periodic reviews are conducted.
* Revision History
  *DRAFT*
